os:
  - "linux"
sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r ./requirements/ci.txt
  - pip install .
script:
  - py.test --verbose ./verboselib ./tests --cov ./verboselib ./tests
after_success:
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false
