# https://ci.appveyor.com/project/oblalex/verboselib

build: false # Not a C# project, build stuff at the test step instead.
environment:
  matrix:
    - PYTHON: "C:/Python37"
    - PYTHON: "C:/Python37-x64"
    - PYTHON: "C:/Python38"
    - PYTHON: "C:/Python38-x64"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -r ./requirements/ci.txt"
  - "%PYTHON%/Scripts/pip.exe install --upgrade --editable ."
test_script:
  - "%PYTHON%/Scripts/py.test --verbose ./verboselib ./tests --cov ./verboselib ./tests"
